# Generated by Django 4.1.3 on 2022-11-08 23:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(max_length=50, null=True, verbose_name='Product name')),
                ('category', models.CharField(choices=[('stationary', 'stationary'), ('electronincs', 'electronics'), ('food', 'food')], max_length=20, verbose_name='product Category')),
                ('price', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=100, null=True)),
                ('stoname', models.CharField(blank=True, max_length=50, null=True, verbose_name='Stock name')),
                ('stoCity', models.CharField(blank=True, max_length=200, null=True, verbose_name='Stock City')),
                ('stoaddress', models.CharField(blank=True, max_length=50, null=True, verbose_name='Stock Address')),
                ('stostatus', models.CharField(blank=True, choices=[('available', 'available'), ('full', 'full')], max_length=20, null=True, verbose_name='Stock Status')),
                ('stophone', models.IntegerField(blank=True, null=True, verbose_name='Stock Phone Number')),
            ],
        ),
        migrations.CreateModel(
            name='suppliers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supname', models.CharField(blank=True, max_length=50, null=True, verbose_name='Supplier name')),
                ('suppCity', models.CharField(blank=True, max_length=200, null=True, verbose_name='Supplier City')),
                ('suppaddress', models.CharField(blank=True, max_length=200, null=True, verbose_name='Supplier Address')),
                ('supphone', models.IntegerField(blank=True, null=True, verbose_name='Supplier Phone Number')),
            ],
        ),
        migrations.CreateModel(
            name='Stockproduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(default=0)),
                ('type', models.CharField(choices=[('1', 'Stock-in'), ('2', 'Stock-Out')], default=1, max_length=2)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.product')),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(null=True)),
                ('category', models.CharField(choices=[('stationary', 'stationary'), ('electronincs', 'electronics'), ('food', 'food')], max_length=20, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.product')),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
